# Generated by Django 3.1.2 on 2020-11-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
