# Generated by Django 3.1.2 on 2020-11-02 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201102_0548'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoEmpleado',
            new_name='TipoUsuario',
        ),
    ]
