# Generated by Django 3.1.2 on 2020-12-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contactofinal_tipocontacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=12)),
                ('valor', models.IntegerField()),
                ('notas', models.CharField(max_length=300)),
                ('valorpresupuestado', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Insumo',
        ),
    ]
