# Generated by Django 3.1.2 on 2020-12-12 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201212_0208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.DeleteModel(
            name='TipoUsuario',
        ),
    ]
