# Generated by Django 3.1.2 on 2020-12-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201212_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombresucursal', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='tiendanombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='ContactoFinal',
        ),
        migrations.DeleteModel(
            name='TipoContacto',
        ),
    ]
